### PR TITLE
text_Balls_en.txt

### PR DESCRIPTION
**Pull request by TheMeq**
For when needed

### CODE REVIEW

**Comment by Strackeror** [comment]
I don't really see why that's needed, they are already in text_Items, and easier to use from there

**Comment by TheMeq** [comment]
Its just that, the ball for my Lugia is listed as a Hyper Potion... i thought you wasn't listing them correctly.

**Comment by Strackeror** [comment]
Oh shit really ? You are right then, i'm gonna need this one
I'll merge it in the next update

**Comment by Strackeror** [comment]
What ball did your lugia have ?
Because text_Balls does not work at all when simply importing and getting the line corresponding to the ID, i'm currently researching on PKHex's code, but this part is pretty obscure

**Comment by TheMeq** [comment]
It's a dream ball

**Pull request merged**
